language: cpp
dist: bionic

addons:
  apt:
    sources:
      - ppa:beineri/opt-qt-5.15.2-bionic
    packages:
      - qt515base
      - qt515tools

script:
  - /opt/qt515/bin/qt515-env.sh
  - qmake
  - make