name: CI for release tags

on:
  push:
    tags:
      - "v*" # matches v1.0.1, v1.2, v2, etc

jobs:
  build:
    name: Build release for ${{ matrix.target }}
    runs-on: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true

      - name: install packages required for the build
        run: |
          sudo apt update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt -qq -y install devscripts equivs lintian
          mk-build-deps -i -s sudo -t "apt --yes --no-install-recommends"

      - name: build source package
        env:
          DEBFULLNAME: "Github Actions"
          DEBEMAIL: "jakob.flierl@gmail.com"
        run: |
          export TARGET=$(. /etc/lsb-release && echo $DISTRIB_CODENAME)
          VERSION="$(git describe --tags | sed -e "s/^v//" -e "s/-/+git/")"
          dch --create \
              --distribution ${TARGET} \
              --package bpp \
              --newversion ${VERSION}~${TARGET}1 \
              "Automatic build from Github"
          debuild -S -sa -us -uc -d

      - name: build binary package
        run: dpkg-buildpackage -b -us -uc

      - name: upload debian package
        uses: softprops/action-gh-release@v2
        with:
          files: ../*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
