name: CI for release tags

on:
  push:
    tags:
      - "v*" # matches v1.0.1, v2, etc

jobs:
  build:
    name: Build release for ${{ matrix.target }}
    runs-on: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - ubuntu-24.04
    steps:
    - name: Set Node.js 24
      run: echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true" >> $GITHUB_ENV

    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: true

    - name: install packages required for the build
      run: |
        sudo apt update -qq
        sudo DEBIAN_FRONTEND=noninteractive apt -qq -y install devscripts equivs lintian
        mk-build-deps -i -s sudo -t "apt --yes --no-install-recommends"

    - name: build source package
      env:
        DEBFULLNAME: "Jakob Flierl"
        DEBEMAIL: "jakob.flierl@gmail.com"
      run: |
        export TARGET=$(. /etc/lsb-release && echo $DISTRIB_CODENAME)
        VERSION="$(git describe --tags | sed -e "s/^v//" -e "s/-/+git/")"
        dch --increment --distribution ${TARGET} -- "Automatic build"
        debuild -S -sa -us -uc -d

    - name: build binary package
      run: dpkg-buildpackage -b -us -uc

    - name: upload debian package
      uses: softprops/action-gh-release@v2
      with:
        files: ../*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}